package assignment1;/* Generated By:JavaCC: Do not edit this line. AssignmentTokeniserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentTokeniserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMIC = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int PLUS_SIGN = 13;
  /** RegularExpression Id. */
  int MINUS_SIGN = 14;
  /** RegularExpression Id. */
  int TILDE = 15;
  /** RegularExpression Id. */
  int PIPE = 16;
  /** RegularExpression Id. */
  int AMP = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int NOT_EQU = 19;
  /** RegularExpression Id. */
  int LESS_THAN = 20;
  /** RegularExpression Id. */
  int LESS_THAN_EQ = 21;
  /** RegularExpression Id. */
  int GREAT_THAN = 22;
  /** RegularExpression Id. */
  int GREAT_THAN_EQ = 23;
  /** RegularExpression Id. */
  int ASSIGN = 24;
  /** RegularExpression Id. */
  int LBR = 25;
  /** RegularExpression Id. */
  int RBR = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int VARIABLE = 28;
  /** RegularExpression Id. */
  int CONSTANT = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int INTEGER = 31;
  /** RegularExpression Id. */
  int BOOLEAN = 32;
  /** RegularExpression Id. */
  int VOID = 33;
  /** RegularExpression Id. */
  int MAIN = 34;
  /** RegularExpression Id. */
  int IF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int TRUE = 37;
  /** RegularExpression Id. */
  int FALSE = 38;
  /** RegularExpression Id. */
  int WHILE = 39;
  /** RegularExpression Id. */
  int BEGIN = 40;
  /** RegularExpression Id. */
  int END = 41;
  /** RegularExpression Id. */
  int IS = 42;
  /** RegularExpression Id. */
  int SK = 43;
  /** RegularExpression Id. */
  int NUM = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int UNDERSC = 47;
  /** RegularExpression Id. */
  int LETTER = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTICOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\"skip\"",
    "<NUM>",
    "<DIGIT>",
    "<ID>",
    "\"_\"",
    "<LETTER>",
  };

}
